/**
* Initializes the DFA object. 
* This file was automatically generated by src/visual/boot.js.
*/let dfa = new DFA(
rankDirection = "LR",
nodeSettings = { style: "filled", fillcolor: "white", shape: "circle" },
nodes = [
    {name: "A", id:"n1", settings: {fillcolor: "green"}}
], 
transistions = [
    {from: "A", to: "B", label: "0"},
    {from: "B", to: "B", label: "0"}
]
)