<<<<<<< HEAD
let dfa = new DFA(
    rankDirection = 'LR', 
 nodeSettings = {style: 'filled', fillcolor: 'white', shape: 'circle'}, 
 nodes = [
{name: '1', id:'5', settings: {fillcolor: 'green'}},
{name: '2', id:'4', settings: {}},
{name: '3', id:'3', settings: {}},
{name: '4', id:'2', settings: {shape: 'doublecircle'}},
{name: '5', id:'1', settings: {shape: 'doublecircle'}},
], 
 transistions = [
 {from: '1', to: '2', label: 'hardcodedatm'},
 {from: '2', to: '3', label: 'hardcodedatm'},
 {from: '3', to: '4', label: 'hardcodedatm'},
] 
 )

=======
/**
* Initializes the DFA object. 
* This file was automatically generated by src/visual/boot.js.
*/
let input = ["0", "0", "1", "0", "1", "1", "1", "0"]
let inputModel = new DFA(
    rankDirection = "LR",
    nodeSettings = {style: "filled", fillcolor: "white", shape: "circle"},
    startID = "n1",
    endIDs = ["n6"],
    nodes = [
        {name: "A", id:"n1"},
        {name: "B", id:"n2"},
        {name: "C", id:"n3"},
        {name: "D", id:"n4"},
        {name: "E", id:"n5"},
        {name: "F", id:"n6"}
    ], 
    transistions = [
        {from: "A", to: "B", label: "0"},
        {from: "A", to: "C", label: "1"},
        {from: "B", to: "B", label: "0"},
        {from: "B", to: "C", label: "1"},
        {from: "C", to: "D", label: "0"},
        {from: "C", to: "E", label: "1"},
        {from: "D", to: "B", label: "1"},
        {from: "E", to: "F", label: "0"}
    ]
)
>>>>>>> ed9622d735ec159eafb6eed3cd5de411805b6c4f
